config/routes.rb
        member do
          get :edit_welcome_email
          post :create_sender_address
          get :check_email_status
          post :resend_verification_email
          get :edit_text_instructions
          get :test_welcome_email
          get :social_media
          get :analytics
          put :social_media, to: 'communities#update_social_media'
          put :analytics, to: 'communities#update_analytics'
          delete :delete_marketplace

          get :topbar, to: redirect("/admin/topbar/edit")
          put :topbar, to: "communities#update_topbar" # PUT request, no redirect
          get :menu_links, to: redirect("/admin/topbar/edit")
          put :menu_links, to: "communities#update_topbar" # PUT request, no redirect

          get :getting_started, to: redirect('/admin/getting_started_guide')

          get :edit_details, to: redirect("/admin/details/edit")
          put :update_details, to: "community_customizations#update_details" # PUT request, no redirect
          get :edit_look_and_feel, to: redirect("/admin/look_and_feel/edit")
          put :edit_look_and_feel, to: "community_customizations#update_look_and_feel" # PUT request, no redirect

          get :settings, to: redirect("/admin/settings")
          put :update_settings # PUT request, no redirect
          get "getting_started_guide", to: redirect("/admin/getting_started_guide")
          get "getting_started_guide/slogan_and_description", to: redirect("/admin/getting_started_guide/slogan_and_description")
          get "getting_started_guide/cover_photo", to: redirect("/admin/getting_started_guide/cover_photo")
          get "getting_started_guide/filter", to: redirect("/admin/getting_started_guide/filter")
          get "getting_started_guide/paypal", to: redirect("/admin/getting_started_guide/paypal")
          get "getting_started_guide/listing", to: redirect("/admin/getting_started_guide/listing")
          get "getting_started_guide/invitation", to: redirect("/admin/getting_started_guide/invitation")

        end
        resources :transactions, controller: :community_transactions, only: :index
        resources :emails
        resources :community_memberships do
          member do
            put :ban
          end
          collection do
            post :promote_admin
            post :posting_allowed
          end
        end
        resource :paypal_preferences, only: :index do

          member do
            get :index, to: redirect("/admin/paypal_preferences")
            post :preferences_update # POST request, no redirect
            get :account_create, to: redirect("/admin/paypal_preferences/account_create")
            get :permissions_verified, to: redirect("/admin/paypal_preferences/permissions_verified")
          end
        end

        resource :stripe_preferences, only: :index do

          member do
            get :index, to: redirect("/admin/paypal_preferences")
            post :preferences_update # POST request, no redirect
            get :account_create, to: redirect("/admin/stripe_preferences/account_create")
            get :permissions_verified, to: redirect("/admin/stripe_preferences/permissions_verified")
          end
        end
      end
      resources :custom_fields do
        collection do
          get :edit_price
          get :edit_location
          post :order
          put :update_price
          put :update_location
        end
      end
      resources :categories do
        member do
          get :remove
          delete :destroy_and_move
        end
        collection do
          post :order
        end
      end
      resources :listing_shapes do
        collection do
          post :order
        end
        member do
          get :close_listings
        end
      end
      resource :plan, only: [:show]
    end

    resources :invitations
    resources :user_feedbacks, :controller => :feedbacks
    resources :homepage do
      collection do
        get :sign_in
        post :join
      end
    end

    resources :listings do
      resources :customer_offers do
        put :accept, on: :member
      end
      member do
        post :follow
        delete :unfollow
      end
      collection do
        get :new_form_content
        get :edit_form_content
        get :more_listings
        get :browse
        get :locations_json
        get :verification_required
        get :listing_lists
      end
      resources :comments, :only => [:create, :destroy]
      resources :listing_images do
        collection do
          post :add_from_file
          put :add_from_url
        end
      end
    end

    resources :listing_images do
      member do
        get :image_status
      end
      collection do
        post :add_from_file
        put :add_from_url
      end
    end

    resources :infos do
      collection do
        get :about
        get :how_to_use
        get :terms
        get :privacy
        get :news
      end
    end
    resource :terms do
      member do
        post :accept
      end
    end
    resources :sessions do
      collection do
        post :request_new_password
        post :change_mistyped_email
      end
    end
    resources :consent
    resource :sms do
      get :message_arrived
    end

    devise_for :people, skip: :omniauth_callbacks, controllers: {confirmations: "confirmations", registrations: "people", omniauth_callbacks: "sessions"}, :path_names => {:sign_in => 'login'}
    devise_scope :person do
      get "/people/confirmation" => "confirmations#show", :as => :confirmation
      put "/people/confirmation" => "confirmations#create"
      get "/people/sign_up" => redirect("/%{locale}/login")

      get "/signup" => "people#new", :as => :sign_up
      get '/people/auth/:provider/setup' => 'sessions#facebook_setup' #needed for devise setup phase hook to work

      resources :people, param: :username, :path => "", :only => :show, :constraints => {:username => /[_a-z0-9]{3,20}/} do
        member do
          get :wall
          get :friend
          get :change_notification_status
          get :offer_list
        end
        collection do
          get 'find_mention'
        end
      end

      resource :stripe_account, only: [] do
        collection do
          post :webhooks
        end
      end

      resources :people, except: [:show] do
        collection do
          get :check_username_availability
          get :check_email_availability
          get :check_email_availability_and_validity
          get :check_invitation_code
          get :create_facebook_based
        end
      end

      resources :people, except: [:show], :path => "" do
        resources :listings do
          member do
            put :close
            put :move_to_top
            put :show_in_updates_email
          end
        end
        resources :person_messages

        resource :inbox, :only => [:show]

        resources :messages, :controller => :conversations do
          collection do
            get :received, to: 'inboxes#show'
          end
          member do
            get :confirm, to: 'confirm_conversations#confirm'
            get :cancel, to: 'confirm_conversations#cancel'
            put :confirmation, to: 'confirm_conversations#confirmation' #TODO these should be under transaction
            get :accept_preauthorized, to: 'accept_preauthorized_conversations#accept'
            get :reject_preauthorized, to: 'accept_preauthorized_conversations#reject'
            put :acceptance_preauthorized, to: 'accept_preauthorized_conversations#accepted_or_rejected'
          end
          resources :messages
          resources :feedbacks, :controller => :testimonials do
            collection do
              put :skip
            end
          end
        end
        resource :paypal_account, only: [:index] do
          member do
            get :ask_order_permission
            get :ask_billing_agreement
            get :permissions_verified
            get :billing_agreement_success
            get :billing_agreement_cancel
          end
        end

        resource :stripe_account, only: [:index] do
          member do
            post :create_account
            post :verify_account
            get :permissions_verified
            get :billing_agreement_success
            get :billing_agreement_cancel
          end
        end

        resources :transactions, only: [:show, :new, :create]
        resource :settings do
          member do
            get :account
            get :notifications
            get :payments
            get :unsubscribe
          end
        end
        resources :testimonials
        resources :emails do
          member do
            post :send_confirmation
          end
        end
        resources :followers
        resources :followed_people
      end # people

    end # devise scope person

    post '/people/:username/add_friend' => "friendships#add_friend", :as => :add_friend
    post '/people/:username/accept_friend' => "friendships#accept_friend", :as => :accept_friend
    post '/people/:username/remove_friend' => "friendships#remove_friend", :as => :remove_friend

    get "/:person_id/messages/:conversation_type/:id" => "conversations#show", :as => :single_conversation

    get '/:person_id/settings/profile', to: redirect("/%{person_id}/settings") #needed to keep old links working

  end # scope locale

  id_to_username = Proc.new do |params, req|
    username = Person.find(params[:person_id]).try(:username)
    locale = params[:locale] + "/" if params[:locale]
    if username
      "/#{locale}#{username}#{params[:path]}"
    else
      "/404"
    end
  end

  get "(/:locale)/people/:person_id(*path)" => redirect(id_to_username), :constraints => {:locale => locale_matcher, :person_id => /[a-zA-Z0-9_-]{22}/}

  get "(/:locale)/:person_id(*path)" => redirect(id_to_username), :constraints => {:locale => locale_matcher, :person_id => /[a-zA-Z0-9_-]{22}/}

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController


  def add_friend
    person = Person.find_by_username(params[:username])
    @current_user.invite person
    if person.privacy.auto_follower?
      person.approve @current_user
    end
    respond_to do |format|
      format.js { render layout: false, locals: {person: person} }
      format.html { redirect_to :back }
    end
  end

  def accept_friend
    person = Person.find_by_username(params[:username])
    @current_user.approve person
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render layout: false, locals: {person: person} }
    end
  end

  def remove_friend
    person = Person.find_by_username(params[:username])
    @current_user.remove_friendship person
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render layout: false, locals: {person: person} }
    end
  end

  def block_friend
    person = Person.find_by_username(params[:username])
    if @current_user.blocked?(person)
      @current_user.unblock(person)
      @text = "Block"
    else
      @current_user.block(person)
      @text = "Unblock"
    end
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render layout: false, locals: {person: person} }
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_follow_unfollow_button.html.erb
<% if @current_user.present? %>
    <div class="follow-button-container follow-button-container-<%= person.id %>">
      <% if @current_user.friend_with? person %>
          <%= link_to remove_friend_path(person.username), :method => "post", :remote => true, :class => "btn btn-primary following" do %>
              <i class="fa"></i>
          <% end %>
      <% else %>
          <% if person.invited_by? @current_user %>
              <%= link_to remove_friend_path(person.username), :method => "post", :remote => true, :class => "btn btn-default pending-follow" do %>
              <% end %>
          <% elsif @current_user.invited_by? person %>
              <%= link_to accept_friend_path(person.username), :method => "post", :remote => true, :class => "btn btn-default" do %>
                  Confirm
              <% end %>
              <%= link_to accept_friend_path(person.username), :method => "post", :remote => true, :class => "btn btn-danger" do %>
                  Delete Request
              <% end %>
          <% else %>
              <%= link_to add_friend_path(person.username), :method => "post", :remote => true, :class => 'btn btn-default follow-user' do %>
                  <i class="fa fa-plus"></i> Follow
              <% end %>
          <% end %>
      <% end %>
    </div>
<% end %>

app/views/friendships/_friend_item.html.erb
<li class="clearfix friend-item-<%= friend.id %>">
  <div class="friend-item">
    <div class="clearfix">
      <div class="profile-pic">
        <%= link_to person_path(friend.username) do %>
            <%= huge_avatar_thumb(friend) %>
        <% end %>
      </div>
      <div class="profile-info">
        <%= link_to person_path(friend.username) do %>
            <%= friend.full_name %>
        <% end %>
        <p class="mutual-friend">
          <% followers = friend.invited %>
          <%= link_to friend_person_path(friend), class: 'follower' do %>
              <%= "#{followers.count} #{'Follower'.pluralize(followers.count)}" %>
          <% end %>
        </p>

        <div class="follow-unfollow-wrapper">
          <% unless current_user?(friend) %>
              <%= render 'friendships/follow_unfollow_button', person: friend %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/friendships/_friend_request.html.erb
<% if friend_request.present? %>
    <h3 class="friendship-header"> <%= friend_request.present? ? "Pending Following #{friend_request.count}" : 'No pending Following' %> </h3>
      <ul class="friend-request-list clearfix">
        <% friend_request.each do |request| %>
            <%= render 'friendships/friend_item', friend: request, person: @person %>
        <% end %>
      </ul>
<% end %>

app/views/friendships/accept_friend.js.erb
$('.follow-button-container-<%= person.id %>').html("<%= escape_javascript(render 'friendships/follow_unfollow_button', :person => person).html_safe %>");
$(".friend-item-<%= person.id %>").remove();
$(".friend-list").append("<%= escape_javascript(render 'friendships/friend_item', friend: person, person: @current_user) %>");

app/views/friendships/add_friend.js.erb
$('.follow-button-container-<%= person.id %>').html("<%= escape_javascript(render 'friendships/follow_unfollow_button', :person => person).html_safe %>");

app/views/friendships/block_friend.js.erb
$(".block_unblock_text").html("<%= @text %>");

app/views/friendships/friend_list.html.erb
<html>
<style>
    body {font-family: "Lato", sans-serif;}

    ul.tab {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }

    /* Float the list items side by side */
    ul.tab li {float: left;}

    /* Style the links inside the list items */
    ul.tab li a {
        display: inline-block;
        color: black;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        transition: 0.3s;
        font-size: 17px;
    }

    /* Change background color of links on hover */
    ul.tab li a:hover {
        background-color: #ddd;
    }

    /* Create an active/current tablink class */
    ul.tab li a:focus, .active {
        background-color: #ccc;
    }

    /* Style the tab content */
    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }
</style>
<body>

<p>Click on the links inside the tabbed menu:</p>

<ul class="tab">
  <li><a href="#" class="tablinks" onclick="openfriend_type(event, 'friend')">Friends   <%= @friends.count  %></a></li>
  <li><a href="#" class="tablinks" onclick="openfriend_type(event, 'mutual_friend')">Mutual Friends   <%= @mutual_friends.count %></a></li>
  <li><a href="#" class="tablinks" onclick="openfriend_type(event, 'following')">Following   <%= @following.count %></a></li>
  <li><a href="#" class="tablinks" onclick="openfriend_type(event, 'follower')">Follower     <%= @follower.count %></a></li>
</ul>

<div id="friend" class="tabcontent">
 <div class="row">
   <% @friends.each do |friend| %>
       <div class="friend-item">

       </div>
   <% end %>
 </div>
</div>

<div id="mutual_friend" class="tabcontent">
  <h3>Paris</h3>
  <p>Paris is the capital of France.</p>
</div>

<div id="following" class="tabcontent">
  <h3>Tokyo</h3>
  <p>Tokyo is the capital of Japan.</p>
</div>

<div id="follower" class="tabcontent">
  <h3>Tokyo</h3>
  <p>Tokyo is the capital of Japan.</p>
</div>

<script>
    function openfriend_type(evt, friend_type) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(friend_type).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>

</body>
</html>

app/views/friendships/remove_friend.js.erb
$('.follow-button-container-<%= person.id %>').html("<%= escape_javascript(render 'friendships/follow_unfollow_button', :person => person).html_safe %>");
$(".friend-item-<%= person.id %>").remove();